name: Tests
env:
  NODE_NO_WARNINGS: true
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: the-guild-org/shared-config/setup@main
        name: Setup Env
        with:
          nodeVersion: 20
          packageManager: pnpm
          packageManagerVersion: 9.5.0

      - name: Lint
        run: pnpm lint

  build-matchstick:
    name: Build Matchstick
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68.0

      - uses: the-guild-org/shared-config/setup@main
        name: Setup Env
        with:
          nodeVersion: 20
          packageManager: pnpm
          packageManagerVersion: 9.5.0

      - name: Install Dependencies
        run: pnpm install

      - name: Build Matchstick Package
        run: pnpm --filter=@graphprotocol/graph-matchstick build

      - name: Upload Matchstick Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: matchstick-build
          path: |
            packages/matchstick/graph-matchstick.*.node
            packages/matchstick/index.js

  cli:
    name: CLI / nodejs v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Matchstick Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: matchstick-build
          path: packages/matchstick/

      - uses: the-guild-org/shared-config/setup@main
        name: Setup Env
        with:
          nodeVersion: ${{ matrix.node-version }}
          packageManager: pnpm
          packageManagerVersion: 9.5.0

      - name: Setup git user information
        run: |
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Build Packages
        run: pnpm build # will also check types

      - name: Run Tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pnpm run test:cli

  event-handler:
    name: Ethereum Basic Event Handlers
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Matchstick Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: matchstick-build
          path: packages/matchstick/

      - uses: the-guild-org/shared-config/setup@main
        name: Setup Env
        with:
          nodeVersion: 20
          packageManager: pnpm
          packageManagerVersion: 9.5.0

      - name: Build Packages
        run: pnpm build

      - name: Should re-link local workspace deps?
        run: pnpm i

      - name: Run Tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pnpm run --filter="example-ethereum-basic-event-handlers" test

  ts:
    name: Graph TS
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Matchstick Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: matchstick-build
          path: packages/matchstick/

      - uses: the-guild-org/shared-config/setup@main
        name: Setup Env
        with:
          nodeVersion: 20
          packageManager: pnpm
          packageManagerVersion: 9.5.0

      - name: Build Packages
        run: pnpm build # will also check types

      - name: Run Tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pnpm run test:ts
